language: node_js 
node_js: stable 

cache:
    apt: true
    directories:
        - node_modules 
before_install:
    - npm install hexo-cli -g

install:
    - npm install 
script:
    - hexo clean 
    - hexo g 
after_script:
    - git clone https://${GH_REF} .deploy_git
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/
    - cd ./public
    - git config user.name "donghao"
    - git config user.email "1185098948@qq.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${ACCESS_TOKEN}@${GH_REF}" master:master 
branches:
    only:
        - master 
env:
    global:
        - GH_REF: github.com/flaskeer/flaskeer.github.io.git 