language: node_js 
node_js: stable 
install:
    - npm install 
script:
    - hexo clean 
    - hexo g 
after_script:
    - cd ./public
    - git init
    - git config user.name "donghao" 
    - git config user.email "1185098948@qq.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${Travis_token}@${GH_REF}" master:master 
branches:
    only:
        - master 
env:
    global:
        - GH_REF: github.com/flaskeer/flaskeer.github.io.git 