language: node_js 
node_js: stable 
install:
    - npm install 
script:
    - hexo clean 
    - hexo g 
after_script:
    - git clone https://${GH_REF} .deploy_git
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/
    - cd ./public
    - git config user.name "your name"
    - git config user.email "your email"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${ACCESS_TOKEN}@${GH_REF}" master:master 
branches:
    only:
        - master 
env:
    global:
        - GH_REF: github.com/flaskeer/flaskeer.github.io.git 